import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dealls.com/sfl');
  await page.getByRole('link', { name: 'Cari Loker' }).click();
  await page.goto('https://dealls.com/sfl');
  await page.getByRole('link', { name: '-on-1 Mentoring' }).click();
  await page.goto('https://dealls.com/sfl');
  await page.getByRole('link', { name: 'Perusahaan', exact: true }).click();
  await page.getByRole('link', { name: 'Perusahaan', exact: true }).click();
  await page.goto('https://dealls.com/sfl');
  await page.getByRole('link', { name: 'Cek CV' }).click();
  await page.getByRole('button', { name: 'Event' }).click();
  await page.getByRole('link', { name: 'SGC Logo SejutaCita Global' }).click();
  await page.goto('https://dealls.com/sgc');
  await page.getByRole('button', { name: 'Event' }).click();
  await page.getByRole('link', { name: 'IDM Logo Indonesia Mengabdi' }).click();
  await page.goto('https://dealls.com/idm');
  await page.getByRole('button', { name: 'Event' }).click();
  await page.getByRole('link', { name: 'SFL Logo SejutaCita Future' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Daftar Sekarang', exact: true }).click();
  const page1 = await page1Promise;
  await page1.getByRole('heading', { name: 'SejutaCita Future Leaders Vol' }).click();
  await page1.getByRole('textbox', { name: 'Nama Lengkap' }).click();
  await page1.getByRole('textbox', { name: 'Nama Lengkap' }).fill('Wisnu Rasyidin Azhari');
  await page1.getByRole('textbox', { name: 'Nama Lengkap' }).press('Enter');
  await page1.getByRole('textbox', { name: 'Nama Lengkap' }).click();
  await page1.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).click();
  await page1.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).fill('02/10/2004');
  await page1.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).click();
  await page1.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).click();
  await page1.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).press('Enter');
  await page1.getByRole('textbox', { name: 'Nomor WhatsApp (jika tidak' }).click();
  await page1.getByRole('textbox', { name: 'Nomor WhatsApp (jika tidak' }).fill('85893438967');
  await page1.getByRole('textbox', { name: 'Nomor WhatsApp (jika tidak' }).press('Enter');
  
  await page1.getByRole('combobox', { name: 'Dari mana kamu mengetahui' }).click();
  await page1.getByRole('option', { name: 'LinkedIn' }).click();
  await page1.getByRole('textbox', { name: 'Provinsi & Kota Domisili Saat' }).click();
  await page1.getByRole('textbox', { name: 'Provinsi & Kota Domisili Saat' }).fill('Klaten, Jawa Tengah');
  await page1.getByText('Kuliah D3/D4/S1/S2').click();
  await page1.getByRole('textbox', { name: 'Instansi Saat Ini (Sekolah/' }).click();
  await page1.getByRole('textbox', { name: 'Instansi Saat Ini (Sekolah/' }).fill('STMIK Amikom Surakarta');
  await page1.getByRole('textbox', { name: 'Ceritakan mengapa kamu ingin' }).click();
  await page1.getByRole('textbox', { name: 'Ceritakan mengapa kamu ingin' }).fill('Saya ingin berkontribusi untuk masa depan indonesia menjadi lebih cerah');
  await page1.getByRole('button', { name: 'Selanjutnya' }).click();
  await page1.locator('[id="radio-group::rf::radio:control:regular"]').click();
  await page1.locator('div').filter({ hasText: /^Personal Motivation Letter$/ }).nth(1).click();
  await page1.getByRole('button', { name: 'Selanjutnya' }).click();
  await page1.getByRole('button', { name: 'Skip, Gak Dulu Deh' }).click();
  await page1.getByRole('textbox', { name: 'Tulis akun utama IG kamu (' }).click();
  await page1.getByRole('textbox', { name: 'Tulis akun utama IG kamu (' }).fill('@rasyidinazhari');
  await page1.getByRole('group').filter({ hasText: 'Like & mention 5 teman yang' }).locator('button').click();
  await page1.getByRole('group').filter({ hasText: 'Like & mention 5 teman yang' }).locator('button').setInputFiles('download.jpeg');
  await page1.getByRole('button', { name: 'Pilih File (Max. 5MB)' }).click();
  await page1.getByRole('button', { name: 'Pilih File (Max. 5MB)' }).setInputFiles('download.jpeg');
  await page1.getByRole('button', { name: 'File Terpilih' }).nth(1).click();
  await page1.getByText('Saya mengerti bahwa sudah').click();
  await page1.getByRole('button', { name: 'File Terpilih' }).nth(1).click();
  await page1.getByRole('button', { name: 'File Terpilih' }).nth(1).setInputFiles('download.jpeg');
  await page1.locator('.size-2\\.5 > path').first().click();
  await page1.getByText('Saya telah membaca Buku').click();
  await page1.getByText('Saya mengetahui bahayanya').click();
  await page1.getByText('Saya menyatakan tidak').click();
  await page1.getByRole('button', { name: 'Selanjutnya' }).click();
  await page1.getByRole('button', { name: 'Selanjutnya' }).click();
  await page1.getByRole('tab', { name: 'Register' }).click();
  await page1.getByRole('tab', { name: 'Sign In' }).click();
  await page1.getByRole('textbox', { name: 'Email' }).click();
  await page1.getByRole('textbox', { name: 'Email' }).fill('');
  await page1.getByRole('tab', { name: 'Register' }).click();
  await page1.getByRole('textbox', { name: 'Email', exact: true }).click();
  await page1.getByRole('textbox', { name: 'Email', exact: true }).fill('wrasyidinazhari99@gmail.com');
  await page1.getByRole('textbox', { name: 'Email', exact: true }).press('Tab');
  await page1.getByRole('textbox', { name: 'Konfirmasi Email' }).fill('wrasyidinazhari99@gmail.com');
  await page1.getByRole('textbox', { name: 'Konfirmasi Email' }).press('Tab');
  await page1.getByRole('textbox', { name: 'Password', exact: true }).fill('@TestQA123');
  await page1.getByRole('textbox', { name: 'Password', exact: true }).press('Tab');
  await page1.getByRole('textbox', { name: 'Konfirmasi Password' }).fill('@TestQA123');
  await page1.getByRole('button', { name: 'Konfirmasi' }).click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('link', { name: 'dealls.com/sfl-komunitas' }).click();
  const page2 = await page2Promise;
});

test('test', async ({ page }) => {
  await page.goto('https://dealls.com/sfl');
  await page.getByRole('button', { name: 'Event' }).click();
  await page.getByRole('link', { name: 'SGC Logo SejutaCita Global' }).click();
  await page.getByRole('heading', { name: 'SejutaCita Global Career', exact: true }).click();
  await page.getByRole('button', { name: 'Event' }).click();
  await page.getByRole('link', { name: 'IDM Logo Indonesia Mengabdi' }).click();
  await page.goto('https://dealls.com/idm');
  await page.getByRole('heading', { name: 'Apa itu Indonesia Mengabdi?' }).click();
  await page.getByRole('button', { name: 'Event' }).click();
  await page.getByRole('link', { name: 'SFL Logo SejutaCita Future' }).click();
  await page.getByRole('heading', { name: 'Apa itu SejutaCita Future' }).click();
});


test('test', async ({ page }) => {
  await page.goto('https://dealls.com/sfl');
  await page.getByRole('navigation').getByRole('link', { name: 'Daftar Sekarang' }).click();
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).click();
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).fill('wad');
  await page.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).click();
  await page.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).click();
  await page.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).fill('12121233');
  await page.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).press('Enter');
  await page.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).click();
  await page.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).dblclick();
  await page.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).fill('02102000');
  await page.getByRole('textbox', { name: 'Nomor WhatsApp (jika tidak' }).click();
  await page.getByRole('textbox', { name: 'Nomor WhatsApp (jika tidak' }).fill('8123123');
  await page.getByRole('textbox', { name: 'Nomor WhatsApp (jika tidak' }).click();
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).click();
  await page.getByRole('textbox', { name: 'Nama Lengkap' }).fill('1wqeqwe');
  await page.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).click();
  await page.getByRole('textbox', { name: 'Tanggal Lahir (min. 13 tahun' }).fill('62/71/2000');
  await page.getByText('Nomor WhatsApp (jika tidak ada, nomor SMS)62No. WhatsApp tidak boleh kosong').click();
  await page.getByRole('textbox', { name: 'Nomor WhatsApp (jika tidak' }).click();
  await page.getByRole('textbox', { name: 'Nomor WhatsApp (jika tidak' }).fill('81231313');
  await page.getByRole('combobox', { name: 'Dari mana kamu mengetahui' }).click();
  await page.getByRole('option', { name: 'Twitter' }).click();
  await page.getByRole('textbox', { name: 'Provinsi & Kota Domisili Saat' }).click();
  await page.getByRole('textbox', { name: 'Provinsi & Kota Domisili Saat' }).fill('awdsa');
  await page.getByRole('radiogroup', { name: 'Jenjang Pendidikan (untuk' }).click();
  await page.getByRole('radiogroup', { name: 'Jenjang Pendidikan (untuk' }).click();
  await page.getByText('Kuliah D3/D4/S1/S2').click();
  await page.getByRole('textbox', { name: 'Instansi Saat Ini (Sekolah/' }).click();
  await page.getByRole('textbox', { name: 'Instansi Saat Ini (Sekolah/' }).fill('asdasd');
  await page.getByText('Nama LengkapTanggal Lahir (').click();
  await page.getByRole('textbox', { name: 'Instansi Saat Ini (Sekolah/' }).fill('asdasda');
  await page.getByRole('textbox', { name: 'Ceritakan mengapa kamu ingin' }).click();
  await page.getByRole('textbox', { name: 'Ceritakan mengapa kamu ingin' }).fill('asdad');
  await page.getByRole('button', { name: 'Selanjutnya' }).click();
  await page.locator('div').filter({ hasText: /^Reguler$/ }).click();
  await page.locator('div').filter({ hasText: /^Personal Motivation Letter$/ }).nth(1).click();
  await page.getByRole('button', { name: 'Selanjutnya' }).click();
  await page.getByRole('button', { name: 'Skip, Gak Dulu Deh' }).click();
  await page.getByRole('textbox', { name: 'Tulis akun utama IG kamu (' }).click();
  await page.getByRole('textbox', { name: 'Tulis akun utama IG kamu (' }).fill('@dsadasd');
  await page.locator('[id="file::rt::trigger"]').click();
  await page.locator('[id="file::rt::trigger"]').setInputFiles('1760643117095.png');
  await page.getByRole('button', { name: 'Pilih File (Max. 5MB)' }).click();
  await page.getByRole('button', { name: 'Pilih File (Max. 5MB)' }).setInputFiles('1760643117095.png');
  await page.locator('[id="file::rv::trigger"]').click();
  await page.locator('[id="file::rv::trigger"]').setInputFiles('1760643117095.png');
  await page.locator('[id="checkbox::r11::control"]').click();
  await page.locator('[id="checkbox::r12::control"]').click();
  await page.locator('[id="checkbox::r13::control"]').click();
  await page.locator('[id="checkbox::r14::control"]').click();
  await page.getByRole('button', { name: 'Selanjutnya' }).click();
  await page.getByRole('button', { name: 'Selanjutnya' }).click();
  await page.getByRole('tab', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('wrasyidinazhari99@gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('button', { name: 'Lupa Password?' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('@Tetew123');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.locator('[id="dialog::ra::positioner"]').click();
});